# Generated by Django 5.2.11 on 2026-05-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='имя покемона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pokemon', verbose_name='картинка покемона')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lon', models.FloatField(verbose_name='долгота')),
                ('Lat', models.FloatField(verbose_name='широта')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entites', to='pokemon_entities.pokemon', verbose_name='ссылка на покемона')),
            ],
        ),
    ]
