# Generated by Django 5.2.11 on 2026-06-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_rename_lat_pokemonentity_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='описание'),
        ),
    ]
